config/routes.rb
TransporteBarato::Application.routes.draw do

  resources :account_activation, only: [:update, :show]

  match "fletes-landing", to: "landings/fletes#home", via: :get
  match "fletes-publicar-anuncio", to: "landings/fletes#places", via: :get, as: :landings_fletes_places
  match "fletes-exito-mas-info", to: "landings/fletes#dates", via: :get, as: :landings_fletes_dates
  match "fletes-gracias-activar-mail", to: "landings/fletes#thanks", via: :get, as: :landings_fletes_thanks

  match "mudanza-landing", to: "landings/mudanzas#home", via: :get
  match "mudanza-publicar-anuncio", to: "landings/mudanzas#places", via: :get, as: :landings_mudanzas_places
  match "mudanza-exito-mas-info", to: "landings/mudanzas#dates", via: :get, as: :landings_mudanzas_dates
  match "mudanza-gracias-activar-mail", to: "landings/mudanzas#thanks", via: :get, as: :landings_mudanzas_thanks

  match "transporte-landing", to: "landings/transportes#home", via: :get
  match "transporte-publicar-anuncio", to: "landings/transportes#places", via: :get, as: :landings_transporte_places
  match "transporte-exito-mas-info", to: "landings/transportes#dates", via: :get, as: :landings_transporte_dates
  match "transporte-gracias-activar-mail", to: "landings/transportes#thanks", via: :get, as: :landings_transporte_thanks

  namespace :landings do
    resources :fletes
    resources :mudanzas
    resources :transportes
  end

  get "/pages/*id" => 'pages#show', :as => :page, :format => false

  resources :meli, only: [:show]
  resources :kmls, only: [:show]
  resources :points
  resources :categories do
    match :children, via: [:get]
  end

  resources :images do
    collection do
      match :create, via: [:put]
    end
  end

  resources :billing_addresses, only: [:create, :update]

  namespace :admin do
    root to: "dashboard#index"

    resources :dashboard
    resources :extra_services
    resources :movement_types
    resources :payment_conditions
    resources :users
    resources :groups
    resources :icons
    resources :templates
    resources :categories
    resources :icons_templates
    resources :vehicle_caracteristics
    resources :transporters
    resources :home_banners
    resources :page_contents
    resources :demands
    resources :budgets
  end

  root to: "home#index"

  localized(I18n.available_locales) do
    resources :notifications, only: [:index, :show] do
      match :highlight, via: [:post]
      match :delete,    via: [:post]

      collection { get :all }
      collection { get :prominent }
      collection { get :deleted }
      collection { get :unread }
    end

    resources :ratings
    resources :credits
    resources :polygons
    resources :clients do
      match :change_password, via: [:get]
    end
    resources :favorites

    resources :demand_steps

    resources :demands do
      match :search, on: :collection, via: [:get, :post]

      resources :comments, only: [:create]

      member do
        match :accomplish,                     via: [:get, :put]
        match :discard,                        via: [:get, :put]
        match :expire,                         via: [:get, :put]
        match :finish_budget_reception_period, via: [:get, :put]
      end

      resources :budgets do
        member do
          match :accept,  via: [:get, :put]
          match :discard, via: [:get, :put]
        end
      end

    end

    resources :budgets do
      resources :comments, only: [:create]
      resources :cash_flow

      member do
        match :receive,  via: [:post]
        match :expire,   via: [:get, :put]
      end
    end

    resources :transporters do
      match :change_password, via: [:get]
      resources :vehicles
      resources :budgets do
        member do
          match :confirm, via: [:post]
          match :cancel, via: [:post]
        end
      end

      resources :coverage_areas
      resources :companies

      resources :reports, only: [:index]
      get "reports/historical_cost"
      get "reports/budget_situation"
    end

    resources :comments, only: [:create] do
      match :read, via: [:get]
    end

    devise_for :users, :controllers => {
      :registrations => 'registrations',
      :omniauth_callbacks => "users/omniauth_callbacks"
    }
  end

end

app/models/icon.rb
class Icon < ActiveRecord::Base
  attr_accessible :depth, :description, :group_id, :high, :image_attributes,
                  :order, :unit, :volume, :weight, :width,
                  :template_ids

  belongs_to :group, inverse_of: :icons
  has_one    :image, as: :imageable, dependent: :destroy, class_name: Image
  has_many   :icons_templates
  has_many   :templates, :through => :icons_templates, inverse_of: :icons

  validates :description, :group, :presence => true

  accepts_nested_attributes_for :image

  def to_s
    self.description
  end

end

app/controllers/admin/icons_controller.rb
class Admin::IconsController < AdminController
  expose(:icons)
  expose(:icon)

  # GET /admin/extra_services
  # GET /admin/extra_services.json
  def index
  end

  # GET /admin/extra_services/1
  # GET /admin/extra_services/1.json
  def show
  end

  # GET /admin/extra_services/new
  # GET /admin/extra_services/new.json
  def new
    icon.build_image
  end

  # GET /admin/extra_services/1/edit
  def edit
    icon.build_image unless icon.image
  end

  # POST /admin/extra_services
  # POST /admin/extra_services.json
  def create
    if icon.save
      redirect_to admin_icons_path, flash: {success: 'El icono fue creado exitosamente.'}
    else
      icon.build_image unless icon.image
      render :new
    end
  end

  # PUT /admin/extra_services/1
  # PUT /admin/extra_services/1.json
  def update
    if icon.update_attributes(params[:icon])
      redirect_to admin_icons_path, flash: {success: 'El icono fue actualizado exitosamente.'}
    else
      icon.build_image unless icon.image
      render :edit
    end
  end

  # DELETE /admin/extra_services/1
  # DELETE /admin/extra_services/1.json
  def destroy
    icon.destroy
    redirect_to admin_icons_path, flash: {success: 'El icono fue eliminado exitosamente.'}
  end
end

app/views/admin/icons/_form.haml
= form_for([:admin, icon]) do |f|
  - if icon.errors.any?
    #error_explanation
      %h6.bold= "#{pluralize(icon.errors.count, "error")} prohibited this icon from being saved:"
      %ul
        - icon.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_field :description
    = f.label :group_id
    = f.select :group_id, Group.all.collect {|p| [ p.description, p.id ] }
    = f.label :order
    = f.text_field :order
    = f.label :volume
    = f.text_field :volume
    = f.label :unit
    = f.text_field :unit
    = f.label :high
    = f.text_field :high
    = f.label :width
    = f.text_field :width
    = f.label :depth
    = f.text_field :depth
    = f.label :weight
    = f.text_field :weight

  .field
    = f.fields_for :image do |image_form|
      = image_form.label :image
      = image_form.file_field :image

  .actions
    = f.submit 'Guardar Icono', class: 'btn btn-primary'

app/views/admin/icons/edit.html.haml
%legend Editando Icono

= render 'form'

= link_to 'Atrás', admin_icons_path, class: 'btn'

app/views/admin/icons/index.html.haml
%h1 Iconos
%br

%table.table
  %tr
    %th Imagen
    %th Descripción
    %th Grupo Descripcion
    %th Orden
    %th Volumen
    %th Unidad
    %th Altura
    %th Ancho
    %th Profundidad
    %th Peso
    %th
    %th
    %th

  - icons.each do |icon|
    %tr
      %td= image_tag icon.image.small if icon.image
      %td= icon.description
      %td= icon.group.description if icon.group
      %td= icon.order
      %td= icon.volume
      %td= icon.unit
      %td= icon.high
      %td= icon.width
      %td= icon.depth
      %td= icon.weight
      %td= link_to 'Mostrar', admin_icon_path(icon), class: 'btn btn-info'
      %td= link_to 'Editar', edit_admin_icon_path(icon), class: 'btn btn-warning'
      %td= link_to 'Borrar', admin_icon_path(icon), method: :delete, data: { confirm: 'Está seguro?' }, class: 'btn btn-danger'

%br

= link_to 'Nuevo Icono', new_admin_icon_path, class: 'btn btn-primary'

app/views/admin/icons/new.html.haml
%h2 Nuevo Icono

= render 'form'

= link_to 'Atrás', admin_icons_path, class: 'btn'

app/views/admin/icons/show.html.haml
%p#notice= notice

.item
  %b Description:
  = icon.description
.item
  %b Grupo:
  = icon.group.description
.item
  %b Orden:
  = icon.order
.item
  %b Volumen:
  = icon.volume
.item
  %b Unidad:
  = icon.unit
.item
  %b Altura:
  = icon.high
.item
  %b Ancho:
  = icon.width
.item
  %b Profunidad:
  = icon.depth
.item
  %b Peso:
  = icon.weight
.item
  %b Imagen:
  = image_tag icon.image

= link_to 'Editar', edit_admin_icon_path(icon), class: 'btn'
= link_to 'Atrás', admin_icons_path, class: 'btn'