config/routes.rb
TransporteBarato::Application.routes.draw do

  resources :account_activation, only: [:update, :show]

  match "fletes-landing", to: "landings/fletes#home", via: :get
  match "fletes-publicar-anuncio", to: "landings/fletes#places", via: :get, as: :landings_fletes_places
  match "fletes-exito-mas-info", to: "landings/fletes#dates", via: :get, as: :landings_fletes_dates
  match "fletes-gracias-activar-mail", to: "landings/fletes#thanks", via: :get, as: :landings_fletes_thanks

  match "mudanza-landing", to: "landings/mudanzas#home", via: :get
  match "mudanza-publicar-anuncio", to: "landings/mudanzas#places", via: :get, as: :landings_mudanzas_places
  match "mudanza-exito-mas-info", to: "landings/mudanzas#dates", via: :get, as: :landings_mudanzas_dates
  match "mudanza-gracias-activar-mail", to: "landings/mudanzas#thanks", via: :get, as: :landings_mudanzas_thanks

  match "transporte-landing", to: "landings/transportes#home", via: :get
  match "transporte-publicar-anuncio", to: "landings/transportes#places", via: :get, as: :landings_transporte_places
  match "transporte-exito-mas-info", to: "landings/transportes#dates", via: :get, as: :landings_transporte_dates
  match "transporte-gracias-activar-mail", to: "landings/transportes#thanks", via: :get, as: :landings_transporte_thanks

  namespace :landings do
    resources :fletes
    resources :mudanzas
    resources :transportes
  end

  get "/pages/*id" => 'pages#show', :as => :page, :format => false

  resources :meli, only: [:show]
  resources :kmls, only: [:show]
  resources :points
  resources :categories do
    match :children, via: [:get]
  end

  resources :images do
    collection do
      match :create, via: [:put]
    end
  end

  resources :billing_addresses, only: [:create, :update]

  namespace :admin do
    root to: "dashboard#index"

    resources :dashboard
    resources :extra_services
    resources :movement_types
    resources :payment_conditions
    resources :users
    resources :groups
    resources :icons
    resources :templates
    resources :categories
    resources :icons_templates
    resources :vehicle_caracteristics
    resources :transporters
    resources :home_banners
    resources :page_contents
    resources :demands
    resources :budgets
  end

  root to: "home#index"

  localized(I18n.available_locales) do
    resources :notifications, only: [:index, :show] do
      match :highlight, via: [:post]
      match :delete,    via: [:post]

      collection { get :all }
      collection { get :prominent }
      collection { get :deleted }
      collection { get :unread }
    end

    resources :ratings
    resources :credits
    resources :polygons
    resources :clients do
      match :change_password, via: [:get]
    end
    resources :favorites

    resources :demand_steps

    resources :demands do
      match :search, on: :collection, via: [:get, :post]

      resources :comments, only: [:create]

      member do
        match :accomplish,                     via: [:get, :put]
        match :discard,                        via: [:get, :put]
        match :expire,                         via: [:get, :put]
        match :finish_budget_reception_period, via: [:get, :put]
      end

      resources :budgets do
        member do
          match :accept,  via: [:get, :put]
          match :discard, via: [:get, :put]
        end
      end

    end

    resources :budgets do
      resources :comments, only: [:create]
      resources :cash_flow

      member do
        match :receive,  via: [:post]
        match :expire,   via: [:get, :put]
      end
    end

    resources :transporters do
      match :change_password, via: [:get]
      resources :vehicles
      resources :budgets do
        member do
          match :confirm, via: [:post]
          match :cancel, via: [:post]
        end
      end

      resources :coverage_areas
      resources :companies

      resources :reports, only: [:index]
      get "reports/historical_cost"
      get "reports/budget_situation"
    end

    resources :comments, only: [:create] do
      match :read, via: [:get]
    end

    devise_for :users, :controllers => {
      :registrations => 'registrations',
      :omniauth_callbacks => "users/omniauth_callbacks"
    }
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :notifiable, polymorphic: true
  belongs_to :notification_type

  attr_accessible :status, :user_id, :sender_attributes, :prominent, :notification_type_id

  delegate :description, :partial, to: :notification_type

  {
    read:    Status::Notification::READ,
    unread:  Status::Notification::UNREAD,
    deleted: Status::Notification::DELETED
  }.each do |key, value|
    define_singleton_method(key) { where(status: value).order("created_at DESC") }
    define_method("#{key}?".to_sym) { status == value }
    define_method(key) do
      self.status = value
      self.save 
    end
  end

  def prominent?
    self.prominent == true
  end

  def self.prominent
    where prominent: true
  end

  def self.no_credit
    joins("LEFT OUTER JOIN notification_types ON notification_types.name = 'NO_CREDIT'")
  end

end

app/models/notification_type.rb
class NotificationType < ActiveRecord::Base
  attr_accessible :description, :name, :partial
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  expose(:notification)
  expose(:notifications) { current_user.notifications.order("created_at DESC") }

  expose(:all_notifications) do
    all = notifications.reject { |n| n.deleted? }
    if params[:tab] == "all"
      Kaminari.paginate_array(all).page(params[:page]).per(10)
    else
      Kaminari.paginate_array(all).page(1).per(10)
    end
  end
  expose(:not_read_notifications) do
    not_read = notifications.unread.reject { |n| n.deleted? }
    if params[:tab] == "not_read"
      Kaminari.paginate_array(not_read).page(params[:page]).per(10)
    else
      Kaminari.paginate_array(not_read).page(1).per(10)
    end
  end
  expose(:prominent_notifications) do
    prominent = notifications.prominent.reject { |n| n.deleted? }
    if params[:tab] == "prominent"
      Kaminari.paginate_array(prominent).page(params[:page]).per(10)
    else
      Kaminari.paginate_array(prominent).page(1).per(10)
    end
  end
  expose(:deleted_notifications) do
    if params[:tab] == "deleted"
      notifications.deleted.page(params[:page]).per(10)
    else
      notifications.deleted.page(1).per(10)
    end
  end

  expose(:next_notification) do
    if notification.unread?
      index = not_read_notifications.index(notification) + 1
      not_read_notifications[index]
    elsif notification.prominent?
      index = prominent_notifications.index(notification) + 1
      prominent_notifications[index]
    elsif notification.deleted?
      index = deleted_notifications.index(notification) + 1
      deleted_notifications[index]
    elsif notification.read?
      index = all_notifications.index(notification) + 1
      all_notifications[index]
    end
  end

  expose(:last_notification) do
    if notification.unread?
      index = not_read_notifications.index(notification) - 1
      not_read_notifications[index]
    elsif notification.prominent?
      index = prominent_notifications.index(notification) - 1
      prominent_notifications[index]
    elsif notification.deleted?
      index = deleted_notifications.index(notification) - 1
      deleted_notifications[index]
    elsif notification.read?
      index = all_notifications.index(notification) - 1
      all_notifications[index]
    end
  end

  def show
    notification.read if notification.unread?
  end

  def highlight
    notification.prominent = params[:prominent]
    notification.save
    render nothing: true
  end

  def delete
    unless notification.deleted?
      notification.deleted
      render nothing: true
    else
      notification.destroy
      render partial: "deleted"
    end
  end

  def all
    render partial: "all", url: { page: params[:page], tab: "all" }
  end

  def prominent
    render partial: "prominent", url: { page: params[:page], tab: "prominent" }
  end

  def deleted
    render partial: "deleted", url: { page: params[:page], tab: "deleted" }
  end

  def unread
    render partial: "unread", url: { page: params[:page], tab: "not_read" }
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_budget_cancelled.html.haml
- demand = notifiable.demand
%p
  = "Han cancelado un presupuesto para tu envío #{demand.description}."
  = link_to "Has click aquí para consultarlo.", demands_url(demand: demand)

app/views/notifications/_budget_changed.html.haml
- demand = notifiable.demand
%p
  = "Han modificado un presupuesto para tu envio #{demand.description}."
  = link_to "Has click aquí para consultarlo.", demands_url(demand: demand, budget: notifiable)

app/views/notifications/_budget_confirmed.html.haml
- demand = notifiable.demand
%p
  = "Han confirmado un presupuesto para tu envío #{demand.description}."
  = link_to "Has click aquí para consultarlo.", demands_url(demand: demand, budget: notifiable)

app/views/notifications/_cheaper_budget.html.haml
%p
  El usuario que ha publicado el envío
  = notifiable.demand_description
  ha recibido un presupuesto más barato que el tuyo.

%p
  Recuerda que puedes rebajar tu presupuesto para tener más opciones de que lo acepten.

app/views/notifications/_confirm_your_budget.html.haml
%p
  = "El envío #{notifiable.demand_description} ha sido modificado."
  = link_to "Has click aquí para confirmar, modificar o descartar tu presupuesto.", demand_url(notifiable.demand)

app/views/notifications/_demand_expired.html.haml
%p
  = "El envío #{notifiable.description} que has presupuestado ha caducado y el usuario no ha aceptado ningún presupuesto."
  = link_to "Has click aquí para consultarlo.", demand_url(notifiable)

app/views/notifications/_new_budget_received.html.haml
- budget, demand = notifiable, notifiable.demand
%p
  = "Tienes un nuevo presupuesto para el envío #{demand.description}."
  = link_to "Has click aquí para consultarlo.", demands_url(budget: budget, demand: budget.demand)

app/views/notifications/_new_demand_to_budget.html.haml
%p
  Tienes un nuevo envío para presupuestar:

%p
  %ul.unstyled
    %li= notifiable.description

%p
  Has
  = link_to 'click aquí', demand_url(notifiable)
  para generar tu presupuesto.

app/views/notifications/_no_credit.html.haml
%p
  Recuerda que tienes presupuestos pendientes de entrega por falta de saldo en tu cuenta.
  = link_to "Has click aquí si deseas aumentar tu saldo.", credits_url

app/views/notifications/_remember_to_valuate_client.html.haml
%p
  Tienes una valoración pendiente de realizar.
  Recuerda que es muy importante tu valoración y opinión tanto para los usuarios como para los transportistas.

app/views/notifications/_remember_to_valuate_transporter.html.haml
%p
  Tienes una valoración pendiente de realizar.
  Recuerda que es muy importante tu valoración y opinión tanto para los usuarios como para los transportistas.

app/views/notifications/_status_tabs.html.haml
%li{ class: (params[:tab].blank? || params[:tab] == "all") ? "active" : "" }
  %a{ href: "#all", 'data-toggle' => "tab"}
    Todas
%li{ class: (params[:tab] == "not_read") ? "active" : "" }
  %a{ href: "#not-read", 'data-toggle' => "tab"}
    No leídas
%li{ class: (params[:tab] == "prominent") ? "active" : "" }
  %a{ href: "#prominent", 'data-toggle' => "tab"}
    Destacadas
%li{ class: (params[:tab] == "deleted") ? "active" : "" }
  %a{ href: "#deleted", 'data-toggle' => "tab"}
    Eliminadas

app/views/notifications/_unread.html.haml
- not_read_notifications.each do |notification|
  = render "notification_row", notification: notification

= paginate not_read_notifications, params: {tab: "not_read", controller: "notifications", action: "index"}

app/views/notifications/index.html.haml
.tb-notify-index
  .tb-navs-container
    %ul.nav.nav-tabs
      = render "status_tabs"

      .right.tb-notify-icons
        %span#delete
          = image_tag "notification/delete.png"

  .tab-content
    #all.tab-pane{ class: (params[:tab].blank? || params[:tab] == "all") ? "active" : "" }
      .dynamic-all
        = render "all"
    #not-read.tab-pane{ class: (params[:tab] == "not_read") ? "active" : "" }
      .dynamic-unread
        = render "unread"
    #prominent.tab-pane{ class: (params[:tab] == "prominent") ? "active" : "" }
      .dynamic-prominent
        = render "prominent"
    #deleted.tab-pane{ class: (params[:tab] == "deleted") ? "active" : "" }
      .dynamic-deleted
        = render "deleted"