config/routes.rb
TransporteBarato::Application.routes.draw do

  resources :account_activation, only: [:update, :show]

  match "fletes-landing", to: "landings/fletes#home", via: :get
  match "fletes-publicar-anuncio", to: "landings/fletes#places", via: :get, as: :landings_fletes_places
  match "fletes-exito-mas-info", to: "landings/fletes#dates", via: :get, as: :landings_fletes_dates
  match "fletes-gracias-activar-mail", to: "landings/fletes#thanks", via: :get, as: :landings_fletes_thanks

  match "mudanza-landing", to: "landings/mudanzas#home", via: :get
  match "mudanza-publicar-anuncio", to: "landings/mudanzas#places", via: :get, as: :landings_mudanzas_places
  match "mudanza-exito-mas-info", to: "landings/mudanzas#dates", via: :get, as: :landings_mudanzas_dates
  match "mudanza-gracias-activar-mail", to: "landings/mudanzas#thanks", via: :get, as: :landings_mudanzas_thanks

  match "transporte-landing", to: "landings/transportes#home", via: :get
  match "transporte-publicar-anuncio", to: "landings/transportes#places", via: :get, as: :landings_transporte_places
  match "transporte-exito-mas-info", to: "landings/transportes#dates", via: :get, as: :landings_transporte_dates
  match "transporte-gracias-activar-mail", to: "landings/transportes#thanks", via: :get, as: :landings_transporte_thanks

  namespace :landings do
    resources :fletes
    resources :mudanzas
    resources :transportes
  end

  get "/pages/*id" => 'pages#show', :as => :page, :format => false

  resources :meli, only: [:show]
  resources :kmls, only: [:show]
  resources :points
  resources :categories do
    match :children, via: [:get]
  end

  resources :images do
    collection do
      match :create, via: [:put]
    end
  end

  resources :billing_addresses, only: [:create, :update]

  namespace :admin do
    root to: "dashboard#index"

    resources :dashboard
    resources :extra_services
    resources :movement_types
    resources :payment_conditions
    resources :users
    resources :groups
    resources :icons
    resources :templates
    resources :categories
    resources :icons_templates
    resources :vehicle_caracteristics
    resources :transporters
    resources :home_banners
    resources :page_contents
    resources :demands
    resources :budgets
  end

  root to: "home#index"

  localized(I18n.available_locales) do
    resources :notifications, only: [:index, :show] do
      match :highlight, via: [:post]
      match :delete,    via: [:post]

      collection { get :all }
      collection { get :prominent }
      collection { get :deleted }
      collection { get :unread }
    end

    resources :ratings
    resources :credits
    resources :polygons
    resources :clients do
      match :change_password, via: [:get]
    end
    resources :favorites

    resources :demand_steps

    resources :demands do
      match :search, on: :collection, via: [:get, :post]

      resources :comments, only: [:create]

      member do
        match :accomplish,                     via: [:get, :put]
        match :discard,                        via: [:get, :put]
        match :expire,                         via: [:get, :put]
        match :finish_budget_reception_period, via: [:get, :put]
      end

      resources :budgets do
        member do
          match :accept,  via: [:get, :put]
          match :discard, via: [:get, :put]
        end
      end

    end

    resources :budgets do
      resources :comments, only: [:create]
      resources :cash_flow

      member do
        match :receive,  via: [:post]
        match :expire,   via: [:get, :put]
      end
    end

    resources :transporters do
      match :change_password, via: [:get]
      resources :vehicles
      resources :budgets do
        member do
          match :confirm, via: [:post]
          match :cancel, via: [:post]
        end
      end

      resources :coverage_areas
      resources :companies

      resources :reports, only: [:index]
      get "reports/historical_cost"
      get "reports/budget_situation"
    end

    resources :comments, only: [:create] do
      match :read, via: [:get]
    end

    devise_for :users, :controllers => {
      :registrations => 'registrations',
      :omniauth_callbacks => "users/omniauth_callbacks"
    }
  end

end

app/controllers/admin/demands_controller.rb
class Admin::DemandsController < AdminController

  expose(:demands){
    #TODO implement ransack!!!

    demands = Demand.where(status: ["ACTIVE", "ACCOMPLISHED", "DISCARDED", "EXPIRED"]).page(params[:page])
    demands = demands.includes(:category)

    if params[:demand]
      demands = demands.where('demands.description ILIKE ?', "%#{params[:demand][:description]}%") unless params[:demand][:description].blank?
      demands = demands.where('demands.status = ?', params[:demand][:status]) unless params[:demand][:status].blank?
      demands = demands.where('categories.ancestry = ?', params[:demand][:category_id]) unless params[:demand][:category_id].blank?
    end

    if params[:dates]
      demands = demands.where('date(demands.created_at) >= to_date(?, \'DD/MM/YYYY\')', params[:dates][:start]) unless params[:dates][:start].blank?
      demands = demands.where('date(demands.created_at) <= to_date(?, \'DD/MM/YYYY\')', params[:dates][:end]) unless params[:dates][:end].blank?
    end

    demands

  }

  def index
    if params[:commit] == "Exportar"
      send_data demands.csv, filename: "export_#{Time.now.to_s}.csv"
    end
  end

end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  include Provider

  skip_before_filter :authenticate_user!, only: [:search, :new, :create, :update]

  before_filter :is_client?, only: [:new], if: :current_user_logged_in?

  expose(:user) { current_user.nil? ? nil : current_user.role }
  expose(:demand) do
    if id = params[:id]
      Demand.find(id)
    elsif params[:demand].respond_to?(:each)
      if category_id = params[:demand][:category]
        params[:demand][:category] = Category.find category_id
      end

      if user
        user.demands.build(params[:demand])
      else
        Demand.new(params[:demand])
      end
    else
      if user
        user.demands.build
      else
        Demand.new
      end
    end
  end

  expose(:demands) do
    results = if current_user.client?
      user.demands
    else
      Demand.all
    end

    results = results.order('created_at DESC')
  end

  expose(:budget) do
    demand.budgets.build(params[:budget])
  end
  expose(:comment) { budget.comments.build }

  expose(:demand_search) do
    if params[:search]
      params[:search].each do |k, v|
        if k =~ /date/ && !v.empty? && !v.nil?
          params[:search][k] = Date.parse(v)
        end

        if k =~ /category/ && !v.empty? && !v.nil?
          params[:search][k].concat v.map { |category_id|
            Category.find(category_id).children.map { |children| children.id }
          }.flatten
        end
      end
    end

    Demand.active.search(params[:search], search_key: :log_search)
  end

  expose(:result) do
    r = demand_search.result

    if params[:search] && vehicle_types = params[:search][:vehicle_types]
      types = vehicle_types.map { |v| "'#{v}'" }.join(",")
      r = r.where("data -> 'vehicle_type' IN (#{types})")
    end

    r.where("expiration_date > ? AND client_id IS NOT NULL", Date.today)
      .order("created_at DESC").page(params[:page]).per(10)
  end

  expose(:active_demands) do
    if demands.respond_to?(:active)
      if params[:status] == "active"
        demands.active.page(params[:page]).per(10)
      else
        demands.active.page(1).per(10)
      end
    else
      Demand.active.page(params[:page]).per(10)
    end
  end

  expose(:accomplished_demands) do
    if demands.respond_to?(:accomplished)
      if params[:status] == "accomplished"
        demands.accomplished.page(params[:page]).per(10)
      else
        demands.accomplished.page(1).per(10)
      end
    else
      Demand.accomplished.page(params[:page]).per(10)
    end
  end

  expose(:discarded_demands) do
    if demands.respond_to?(:discarded)
      if params[:status] == "discarded"
        demands.discarded.page(params[:page]).per(10)
      else
        demands.discarded.page(1).per(10)
      end
    else
      Demand.discarded.page(params[:page]).per(10)
    end
  end
  expose(:categories)              { Category.roots }
  expose(:vehicle_characteristics) { VehicleCaracteristic.all }
  expose(:extra_services)
  expose(:active_budgets)          { demand.blank? ? [] : demand.active_budgets }
  expose(:provider)                { Provider::STANDARD }

  # GET /demands
  # GET /demands.json
  def index
    if params[:budget] && params[:demand]
      a_supposed_sent_budget = Budget.find(params[:budget])
      if a_supposed_sent_budget.sent?
        credit = Credit.new(amount: (a_supposed_sent_budget.demand.price * -1))
        credit.movement_type = MovementType.find('BUDGET_VIEWED')
        credit.budget = a_supposed_sent_budget
        credit.user = a_supposed_sent_budget.user
        credit.save
        a_supposed_sent_budget.receive
      end
    end
  end

  # GET /demands/1
  # GET /demands/1.json
  def show
    @category = demand.category
    @groups = []

    if !@category.templates.empty?
      @groups = @category.templates.first.icons.collect{ |icon| icon.group }.uniq
    end

    if @category.parent
      if !@category.parent.templates.empty?
        @groups << @category.parent.templates.first.icons.collect{ |icon| icon.group }.uniq
      end
    end

    @groups.compact!
  end

  # GET /demands/new
  # GET /demands/new.json
  def new
    demand.build_origin
    demand.build_destiny
    demand.build_destiny_information
    demand.build_origin_information

    @category = Category.where(name: 'Mudanzas').first.children.first
    @groups = []

    if !@category.templates.empty?
      @groups = @category.templates.first.icons.collect{ |icon| icon.group }.uniq
    end

    if @category.parent
      if !@category.parent.templates.empty?
        @groups << @category.parent.templates.first.icons.collect{ |icon| icon.group }.uniq
      end
    end

    @groups.compact!
  end

  # GET /demands/1/edit
  def edit
    @category = demand.category
    @groups = []

    if !@category.templates.empty?
      @groups = @category.templates.first.icons.collect{ |icon| icon.group }.uniq
    end

    if @category.parent
      if !@category.parent.templates.empty?
        @groups << @category.parent.templates.first.icons.collect{ |icon| icon.group }.uniq
      end
    end

    @groups.compact!

    session[:demand_id] = demand.id

    redirect_to demand_steps_url
  end

  # POST /demands
  # POST /demands.json
  def create
    demand.status = Status::Demand::FIRST_STEP unless params[:demand][:status]
    demand.image_ids = params[:images]

    unless params[:demand][:budget_hosting_expiration_date].blank?
      demand.expiration_date = Date.parse(params[:demand][:budget_hosting_expiration_date]) + 15.days
    end

    if demand.from_landing? and demand.category.ancestry
      demand.description = demand.category.name
    end

    if demand.save
      session[:demand_id] = demand.id

      if demand.from_landing?
        if demand.category.name == 'Fletes'
          redirect_to landings_fletes_dates_url
        else
          redirect_to landings_mudanzas_dates_url
        end
      else
        redirect_to demand_steps_url
      end

    else
      @category = demand.category
      @groups = []

      if !@category.templates.blank?
        @groups = @category.templates.first.icons.collect{ |icon| icon.group }.uniq
      end

      if @category.parent
        if !@category.parent.templates.blank?
          @groups << @category.parent.templates.first.icons.collect{ |icon| icon.group }.uniq
        end
      end

      @groups.compact!

      if demand.from_landing?
        if demand.category.name == "Fletes"
          redirect_to landings_fletes_places_url,
            flash: {
              demand_errors: demand.errors,
              demand: demand }
        else
          redirect_to landings_mudanzas_places_url,
            flash: {
              demand_errors: demand.errors,
              demand: demand }
        end
      else
        render :new
      end
    end
  end

  # PUT /demands/1
  # PUT /demands/1.json
  def update
    params[:images] ||= []
    params[:images] << demand.image_ids
    demand.image_ids = params[:images].flatten

    if !params[:demand][:budget_hosting_expiration_date].blank?
      demand.expiration_date = Date.parse(params[:demand][:budget_hosting_expiration_date]) +
        15.days
    elsif !params[:demand][:origin_information_attributes][:delivery_date_from].blank?
      demand.budget_hosting_expiration_date = Date.parse(
        params[:demand][:origin_information_attributes][:delivery_date_from])
      demand.expiration_date = Date.parse(
        params[:demand][:origin_information_attributes][:delivery_date_from]) + 15.days
    end

    session[:demand_id] = demand.id

    if demand.update_attributes(params[:demand])
      if demand.from_landing?
        if demand.category.name == 'Fletes'
          redirect_to landings_fletes_thanks_url
        else
          redirect_to landings_mudanzas_thanks_url
        end
      else
        redirect_to demand_steps_url
      end
    else
      @category = demand.category
      @groups = []

      if !@category.templates.blank?
        @groups = @category.templates.first.icons.collect{ |icon| icon.group }.uniq
      end

      if @category.parent
        if !@category.parent.templates.blank?
          @groups << @category.parent.templates.first.icons.collect{ |icon| icon.group }.uniq
        end
      end

      @groups.compact!

      if demand.from_landing?
        if demand.category.name == "Fletes"
          redirect_to landings_fletes_dates_url,
            flash: {
              demand_errors: demand.errors,
              demand: demand }
        else
          redirect_to landings_mudanzas_dates_url,
            flash: {
              demand_errors: demand.errors,
              demand: demand }
        end
      else
        redirect_to demand_steps_url(demand_id: demand.id)
      end
    end
  end

  # DELETE /demands/1
  # DELETE /demands/1.json
  def destroy
    demand.destroy
    redirect_to demands_url
  end

  def accomplish
    demand.accomplish
    redirect_to demands_url
  end

  def discard
    demand.discard
    redirect_to demands_url
  end

  def search
  end

  def expire
    if current_user.client?
      demand.expire
      render text: "El envio '#{demand.description}' ha expirado"
    else
      render text: "Para realizar la accion es necesario iniciar sesion como usuario."
    end
  end

  def finish_budget_reception_period
    if current_user.client?
      demand.finish_budget_reception_period
      render text: "El periodo de recepcion del envio '#{demand.description}' ha finalizado"
    else
      render text: "Para realizar la accion es necesario iniciar sesion como usuario."
    end
  end

end

app/helpers/demands_helper.rb
module DemandsHelper

  def budget_class_by_status(budget)
    if budget.sent? || budget.updated? || budget.confirmed?
      "sent"
    end
  end

end

app/views/demands/_active_demands.html.haml
#actives.tb-active-demands.lightgrey.tab-pane{ class: (params[:status].nil? || params[:status] == "active") ? 'active' : nil }
  - active_demands.each do |demand|
    //Titulo de acordion
    .tb-accordion-demand
      - if demand.has_new_comments?(current_user) || demand.has_new_budgets?
        %span.tb-accordion-iconbox !
      %span.tb-accordion-demand-title
        %span.tb-demand-title-text= demand.description.truncate(20)
        %span.orange-text.tb-accordion-demand-number.bold
          = "(#{demand.active_budgets.size})"

      %span.tb-accordion-demand-date= demand.expiration_date.strftime("%d/%m/%Y") if demand.expiration_date

      %span.tb-accordion-demand-info
        Origen:
        = demand.origin.to_s(:short) if demand.origin

      %span.tb-accordion-demand-info
        Destino:
        = demand.destiny.to_s(:short) if demand.destiny

      .right.tb-accordion-demand-btns
        - if current_user.has_role? :user
          = link_to 'Ver', demand, class: "button small white"
          = link_to 'Modificar', edit_demand_path(demand), class: "button small white"
          = link_to 'Cancelar',  discard_demand_path(demand), class: "button small white", confirm: "Esta seguro?"

          - if demand.active_budgets.size > 0
            %button{ "type" => "button", "data-toggle" => "collapse", "data-target" => "##{dom_id(demand)}", "id" => "button-demand_#{demand.id}" }
              &nbsp;

        - elsif current_user.has_role? :transporter
          = link_to 'Ver', demand, class: "button small white"
          = link_to 'Presupuestar', new_demand_budget_path(demand), class: "button small white"

    //Cuerpo de acordion
    .tb-accordion-demand-body.collapse{ id: dom_id(demand), class: accordion_class(params[:demand], demand.id), style: accordion_style(params[:demand], demand.id) }
      - demand.active_budgets.each do |budget|
        .clear
          .tb-accordion-budget.clear{ class: budget_class(budget) }
            .one-third
              %span.tb-accordion-budget-price= number_to_currency budget.price, precision: 0
              %span.tb-accordion-budget-rating
                - if budget.transporter.received_ratings.empty?
                  Transportista nuevo
                - else
                  = stars(budget.transporter.total_rating, budget.transporter.received_ratings.size)
            .one-third
              %span.tb-accordion-budget-date= "Valido hasta #{budget.expiration_date.strftime("%d/%m/%Y")}" if budget.expiration_date
            .one-third.last
              .tb-accordion-budget-state
                - if budget.has_new_comments?(current_user)
                  %span.tb-accordion-iconbox= budget.new_comments(current_user).size

                %span= budget_status_label(budget, current_user)
                %button{ "type" => "button", "data-toggle" => "collapse", "data-target" => "##{dom_id(budget)}", "id" => "button-budget_#{budget.id}", "class" => "budget-button" }
                  &nbsp;
          .accordion-body.collapse.budget-info{ id: dom_id(budget), class: "#{budget_class_by_status(budget)} #{accordion_class(params[:budget], budget.id)}", style: accordion_style(params[:budget], budget.id) }
            = render partial: 'transporter', locals: { demand: demand, budget: budget, transporter: budget.transporter, rating: nil }

  = paginate active_demands, params: {status: "active"}

app/views/demands/_form.html.haml
.tb-demands-form

  .tabbable.tabs-left
    - if demand.new_record?
      %ul.nav-tabs.categories
        - Category.roots.order("categories.order ASC").each do |category|
          %li{class: (category.name == 'Mudanzas' ? 'active' : '')}
            %a{ 'data-toggle' => "tab", 'href' => "##{category.id}"}
              = category.name
    - else
      .tb-module-header
        %h5.title.orange-text
          = demand.category.parent
          %span.black  >
          = demand.category
    .tab-content.lightgrey
      - if demand.new_record?
        - Category.roots.each do |category|
          .tab-pane{class: (category.name == 'Mudanzas' ? 'active' : ''), id: category.id}
            - category.children.order("categories.order ASC").each do |subcategory|
              = link_to subcategory.name, category_path(subcategory), remote: true, class: "button small #{subcategory.id == @category.id ? 'orange' : 'white'} category-trigger", id: "category-#{subcategory.id}"

      = form_for demand, html: {class: ' ', id: 'demand-form'} do |f|

        - if demand.errors.any?
          #error_explanation.tb-module-container
            %h6.bold= "No se pudo crear el envío, verifique los siguientes errores:"
            %ul
              - demand.errors.full_messages.each do |msg|
                %li= msg

        //Titulo acordion
        .tb-accordion-title.orange.clear
          %h5.title
            1.
            %span.white Detalles del envío

            %span.right.white.accordion-button
              %i.icon-minus.accordion-button

        //Bloque del acordion
        .tb-module-container.clear
          .tb-module-row.clear.sub-categories
            - if @category
              = hidden_field_tag :parent_category,  @category.parent.id if @category.parent

              = render template: "categories/#{"#{@category.parent.normalized_name}/" if @category.parent}#{@category.normalized_name}", locals: {form: f}

          //Nueva fila
          .tb-module-row.clear
            .one-half
              .form.bg-white.tb-detail-box
                %h5.title
                  Imagenes

                #image-form
                  .field
                    = fields_for :image do |image_form|
                      %span.fileinput-button.thumbnail
                        = image_form.file_field :image

                  .fotos
                    - demand.images.each do |image|
                      = render image
            .one-half.last
              .tb-dimmensions
                .form.tb-detail-box
                  = check_box_tag :meli
                  = label_tag :meli, "Este articulo es de MercadoLibre?", class: "control-label custom-checkbox"

                  #meli-box{style: "display:none;"}
                    .control-group
                      = label_tag 'Número artículo', nil, class: "control-label"
                      = text_field_tag :meli_item_id

                    %button{type: "button", id: "meli-button", class: "button medium orange", autocomplete: 'off', "data-loading-text" => "Importando..."}
                      Importar detalles
                  .tb-module-row.clear
                    %h5.title Descripción
                    = f.text_area :description, :rows => 1

                  %h5.title Detalles adicionales
                  = f.text_area :detail, :rows => 3

        //Titulo acordion
        .tb-accordion-title.orange.clear
          %h5.title
            2.
            %span.white Servicios extras

            %span.right.white.accordion-button
              %i.icon-plus

        //Bloque del acordion
        .tb-module-container.clear{style: 'display:none;'}
          - slices = extra_services.each_slice(extra_services.size / 2 + extra_services.size % 2)
          - slices.each do |extra_services_slice|
            .one-half{class: "#{extra_services_slice != slices.first ? 'last' : '' }"}
              .form.tb-demands-extra-services.tb-detail-box.tb-checkbox-list
                - extra_services_slice.each do |extra_service|
                  .control-group
                    = check_box_tag "demand[extra_service_ids][]", extra_service.id, demand.extra_services.include?(extra_service), id: dom_id(extra_service)
                    = label_tag dom_id(extra_service), extra_service.description, class: "control-label custom-checkbox"

        //Titulo acordion
        .tb-accordion-title.orange.clear
          %h5.title
            3.
            %span.white Información del origen y destino
            %span.right.white.accordion-button
              %i.icon-plus.accordion-button

        /Bloque del acordion
        #demand-form-map-container.tb-module-container.clear.lightgrey

          //Nueva fila
          .tb-module-row.clear
            .one-half
              .form.tb-detail-box
                %h5.title Información de origen
                = f.fields_for :origin do |origin_form|
                  = render 'addresses/form', {:form => origin_form}

                = f.fields_for :origin_information do |origin_information_form|
                  = render 'location_informations/form', {form: origin_information_form, date_ranges: ["Retirar el día", "Retirar antes del día", "Retirar después del día", "Retirar entre los días"]}

            .one-half.last
              .form.tb-detail-box
                %h5.title Información de destino
                = f.fields_for :destiny do |destiny_form|
                  = render 'addresses/form', {:form => destiny_form}

                = f.fields_for :destiny_information do |destiny_information_form|
                  = render 'location_informations/form', {form: destiny_information_form, date_ranges: ["Entregar el día", "Entregar antes del día", "Entregar después del día", "Entregar entre los días"]}

              = f.hidden_field :distance
              = f.hidden_field :status

          //Nueva fila
          .tb-module-row.clear
            .map-container
              #genius-map{style: 'height: 400px;'}
              .distance

          //Nueva fila
          .tb-module-row.clear
            .one-half
              .form.tb-detail-box
                .control-group
                  .tb-datepicker-expiration
                    = f.label 'Recibir presupuestos hasta el:'
                    .datepicker-field
                      - unless f.object.budget_hosting_expiration_date.nil?
                        = f.text_field :budget_hosting_expiration_date, value: l(f.object.budget_hosting_expiration_date), class: 'datepicker'
                      - else
                        = f.text_field :budget_hosting_expiration_date, class: 'datepicker'
                    %label#expiration_notification
            .one-half.last
              .tb-demands-submit-btn
                = f.submit 'Publicar Envio', class: 'button large orange'

app/views/demands/_transporter.html.haml
.tb-module-container.lightgrey.clear
  .one-half
    .form.tb-detail-box.bg-white
      %h5.title Información de contacto

      %p= transporter.user.full_name
      %p= transporter.company.phone_number
      %p= transporter.email
      %p.text-align-right.right
        - if transporter.company and transporter.company.image
          = link_to image_tag(transporter.company.image.icon), transporter.company.image.to_s, class: 'colorbox-gallery'

      = link_to "Ver Perfil", transporter, class: 'button medium orange capitalize'

      %hr

      .field.tb-transporter-detail
        %span.bold
          Empresa:
        = transporter.company.name
      .field.tb-transporter-detail
        %span.bold
          Tipo de empresa:
        = transporter.company.company_type
      .field.tb-transporter-detail
        %span.bold
          Forma de pago:
        = transporter.company.payment_methods.map { |payment_method| payment_method.name }.join(" - ")

      .field.tb-transporter-detail
        %span.bold
          Condiciones de pago:
        = transporter.company.payment_conditions.map { |payment_condition| payment_condition.name }.join(" - ")

      .field.tb-transporter-detail
        %span.bold
          Seguro:
        = transporter.company.license_and_insurance

  .one-half.last
    .tb-module-row
      .form.tb-detail-box.bg-white
        %h5.title
          Observaciones
          %span.orange-text=  "(#{budget.comments.size})"

        .tb-comment-box
          .tb-comments#tb-comments
            - budget.comments.each do |comment|
              .comment{class: (comment.user.transporter? ? '' : 'orange-text'), id: comment.unread? ? comment.id : "" }
                %span.bold= comment.user.transporter? ? 'T:' : 'U:'
                = comment.message

          - unless rating
            = form_for [budget, Comment.new] do |f|
              = f.text_field :message, placeholder: 'Escriba aca su mensaje'
              = f.submit 'Enviar Respuesta', :class => 'button medium orange capitalize'

    - if rating
      = form_for rating do |f|
        .tb-module-row
          .form.tb-detail-box.bg-white
            %h5.title
              Valoración

              %span.rating-face.negative-face -1
              %span.rating-face.neutral-face 0
              %span.rating-face.positive-face 1

            = f.hidden_field :points
            = f.text_area :comment, placeholder: 'Escriba aca su comentario'

        .right= f.submit 'GUARDAR', class: 'button medium orange'

    - if budget.active? && !budget.cancelled?
      .buttons-group.text-align-center
        = link_to 'Aceptar Presupuesto', accept_demand_budget_path(demand, budget), class: "button large orange"
        = link_to 'Descartar Presupuesto', discard_demand_budget_path(demand, budget), class: "button large orange"

app/views/demands/edit.html.haml
= render 'form'

app/views/demands/new.html.haml
.tb-demands-form.lightgrey
  = form_for demand, url: demands_path do |f|
    = hidden_field_tag "demand[provider]", provider
    - if demand.errors.any?
      #error_explanation.tb-module-container
        %h6.bold= "No se pudo crear el envío, verifique los siguientes errores:"
        %ul
          - demand.errors.full_messages.each do |msg|
            %li= msg

    .tb-module-container
      .tb-module-row
        .one-half
          .form.bg-white.tb-detail-box
            = select_tag "categories", options_from_collection_for_select(categories, "id", "name"), prompt: "¿Qué deseas enviar?", class: "input-full-width tb-module-row"

            = f.fields_for :origin, Address.new do |origin_form|
              = origin_form.label "Origen"
              = origin_form.text_field :street_line2, class: 'input-full-width'

              = origin_form.hidden_field :city
              = origin_form.hidden_field :country
              = origin_form.hidden_field :state
              = origin_form.hidden_field :street_line1
              = origin_form.hidden_field :administrative_area
              = origin_form.hidden_field :neighborhood
              = origin_form.hidden_field :latitude
              = origin_form.hidden_field :longitude


        .one-half.last
          .form.bg-white.tb-detail-box
            = select_tag "demand[category]", nil, prompt: "Seleccionar una subcategoría", class: "input-full-width tb-module-row"

            = f.fields_for :destiny, Address.new do |destiny_form|
              = destiny_form.label "Destino"
              = destiny_form.text_field :street_line2, class: 'input-full-width'

              = destiny_form.hidden_field :city
              = destiny_form.hidden_field :country
              = destiny_form.hidden_field :state
              = destiny_form.hidden_field :street_line1
              = destiny_form.hidden_field :administrative_area
              = destiny_form.hidden_field :neighborhood
              = destiny_form.hidden_field :latitude
              = destiny_form.hidden_field :longitude

      .tb-module-row.clear
        .one-half &nbsp;
        .one-half.last.tb-demands-submit-btn= f.submit 'Siguiente', class: 'button large orange'

app/views/demands/search.html.haml
.tb-demands-search
  .row-fluid.search
    .span3
      
      %h5.title Definir la búsqueda

      .clear
        = search_form_for(demand_search, class: "search-form", url: search_demands_path, method: :post) do |f|
          .accordion
            .accordion-group
              = render 'demands/filters/categories', categories: categories
              = render 'demands/filters/location'
              = render 'demands/filters/dimentions'
              = render 'demands/filters/dates'
              = render 'demands/filters/vehicles_type'
              = render 'demands/filters/description'

              .control-group.inline
                %input#delete-filters{ type: "button", class: "button medium orange capitalize", value: "Borrar Filtros" }
                = f.submit "Aplicar filtros", class: "button medium orange capitalize", id: "apply-filters"

    .span9
      .tb-demands-search-container.lightgrey
        = render 'demands/filters/results'